apiVersion: v1
kind: Service
metadata:
  name: game-app-service
spec:
  type: NodePort
  selector:
    app: game-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-app-deployment
  labels:
    app: game-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: game-app
  template:
    metadata:
      labels:
        app: game-app
    spec:
      containers:
      - name: game-app
        image: mattocodes/testapp:latest
        ports:
        - containerPort: 8080
